model_config:
  linear_input_channels: 60
  resblock_channels: 1
num_classes: 17930
train_config:
  batch_size: 4096
  epochs: 1
  gpu: 1
  lr_scheduler:
    gamma: 0.9
    milestones:
    - 5
    - 8
    - 10
    - 12
    - 14
    - 16
    - 18
    - 20
  num_workers: 0
  optimizer:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.01
  seq_max_len: 120
